
server:
  port: 8081
  servlet:
    context-path: /api/users
  error:
    include-message: always
    include-stacktrace: always

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fitness_user_db?serverTimezone=UTC
    username: root
    password: pass
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
  mail:
    host: smtp-relay.brevo.com
    port: 587
    username: 8c83f5001@smtp-brevo.com
    password:  Cp9mhAO4bFjtwEWX
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          from: anupamahera2022@gmail.com


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret:
    key: nKmK7yZK1Fo0jvE4rRyjK2xv1YjFIXE+72S7QUhIj6w=

